"""
BUILD GAP Code Tracker — SKILL_TRAINING_LAWS_v03 §5

Tracks all gap codes across the build process:
  H: Handcraft violations     Q: Quality threshold failures
  AB: A/B run problems        CA: Cognitive architecture gaps
  TI: Trigger incoherence     PL: Placeholder laundering
  SC: Score gaming            ML: Meta-learning failures
  ME: Meta-evaluation gaps

Every gap is tracked with: code, severity, component, fix_strategy
"""

from __future__ import annotations

import json, time, re, hashlib
from dataclasses import dataclass, field, asdict
from typing import Optional, List, Dict, Set, Tuple
from enum import Enum
import logging

logger = logging.getLogger("GAP")


class GAPCategory(str, Enum):
    HANDCRAFT = "H"      # H-01 script-generated, H-02 template not filled, H-03 parafrase
    QUALITY = "Q"        # Q-01 κ under threshold, Q-02 training data κ under 0.80
    AB_RUN = "AB"        # AB-01 fake run, AB-02 multiple variables, AB-03 no causal
    COGNITIVE = "CA"     # CA-01 generic CoT, CA-02 missing decision point
    TRIGGER = "TI"       # TI-01 SKILL.md ≠ TRAINING_PROMPT.md
    PLACEHOLDER = "PL"   # PL-01 placeholder string in final content
    SCORE = "SC"         # SC-01 generic Q/A, SC-02 κ-rubric gaming
    METALEARN = "ML"     # ML-01 missing prompt, ML-02 describes skill not learning
    METAEVAL = "ME"      # ME-01 eval without meta-eval, ME-02 no false negatives


# Full gap code definitions per SKILL_TRAINING_LAWS_v03 §5
GAP_CODES: Dict[str, dict] = {
    # H — Handcraft
    "H-01": {"name": "SCRIPT_GENERATED",    "cat": "H",  "severity": 5, "desc": "Content was generated by an external script, not by the subagent itself"},
    "H-02": {"name": "TEMPLATE_NOT_FILLED", "cat": "H",  "severity": 4, "desc": "Template variables were not filled in — raw {{var}} remains"},
    "H-03": {"name": "PARAFRASE_VIOLATION", "cat": "H",  "severity": 3, "desc": "Content is a parafrase of the prompt instead of original work"},
    # Q — Quality
    "Q-01": {"name": "KAPPA_UNDER_THRESHOLD",      "cat": "Q",  "severity": 5, "desc": "κ_SDCK below 0.95 packaging threshold"},
    "Q-02": {"name": "TRAINING_DATA_KAPPA_LOW",    "cat": "Q",  "severity": 4, "desc": "Training data κ below 0.80"},
    # AB — A/B Run
    "AB-01": {"name": "FAKE_RUN",             "cat": "AB", "severity": 5, "desc": "A/B run was faked — not actually independent"},
    "AB-02": {"name": "MULTIPLE_VARIABLES",   "cat": "AB", "severity": 3, "desc": "A/B run changed more than one variable"},
    "AB-03": {"name": "NO_CAUSAL_EXPLANATION","cat": "AB", "severity": 4, "desc": "A/B divergence lacks causal explanation"},
    # CA — Cognitive Architecture
    "CA-01": {"name": "GENERIC_CHAIN_OF_THOUGHT", "cat": "CA", "severity": 4, "desc": "Generic CoT without skill-specific reasoning"},
    "CA-02": {"name": "MISSING_DECISION_POINT",   "cat": "CA", "severity": 5, "desc": "Critical decision point not modeled in reasoning"},
    "CA-03": {"name": "MISSING_FAILURE_MODE",     "cat": "CA", "severity": 4, "desc": "Failure modes not addressed in reasoning"},
    # TI — Trigger
    "TI-01": {"name": "TRIGGER_INCOHERENCE", "cat": "TI", "severity": 5, "desc": "SKILL.md content differs from TRAINING_PROMPT.md"},
    # PL — Placeholder
    "PL-01": {"name": "PLACEHOLDER_LAUNDERING", "cat": "PL", "severity": 5, "desc": "Placeholder strings present in final packaged content"},
    # SC — Score Gaming
    "SC-01": {"name": "GENERIC_QA",       "cat": "SC", "severity": 4, "desc": "Q/A answers are generic rather than skill-specific"},
    "SC-02": {"name": "KAPPA_RUBRIC_GAMING", "cat": "SC", "severity": 5, "desc": "Systematically gaming κ_SDCK rubric"},
    # ML — Meta-Learning
    "ML-01": {"name": "MISSING_PROMPT",       "cat": "ML", "severity": 4, "desc": "Build prompt not preserved in repository"},
    "ML-02": {"name": "DESCRIBES_NOT_LEARNS", "cat": "ML", "severity": 3, "desc": "Describes skill instead of actual learning process"},
    "ML-03": {"name": "UNMEASURABLE_TRAJECTORY","cat":"ML","severity": 4, "desc": "Learning trajectory cannot be measured"},
    # ME — Meta-Evaluation
    "ME-01": {"name": "EVAL_WITHOUT_METAEVAL", "cat": "ME", "severity": 4, "desc": "Evaluation conducted without meta-evaluation layer"},
    "ME-02": {"name": "NO_FALSE_NEGATIVES",    "cat": "ME", "severity": 5, "desc": "Test set contains no false negative cases"},
    "ME-03": {"name": "NO_FALSE_POSITIVES",    "cat": "ME", "severity": 5, "desc": "Test set contains no false positive cases"},
}


@dataclass
class GAPRecord:
    """Single gap occurrence"""
    gap_code: str
    component: str          # Which component (file/module)
    description: str
    severity: int           # 1-5
    detected_at: float
    resolved_at: Optional[float] = None
    resolution: Optional[str] = None
    fix_strategy: str = ""  # How to fix
    kappa_before: float = 0.0
    kappa_after: float = 0.0

    def to_dict(self) -> dict:
        return {
            "gap_code": self.gap_code,
            "component": self.component,
            "description": self.description,
            "severity": self.severity,
            "detected_at": self.detected_at,
            "resolved_at": self.resolved_at,
            "resolution": self.resolution,
            "fix_strategy": self.fix_strategy,
            "kappa_before": self.kappa_before,
            "kappa_after": self.kappa_after,
        }

    @property
    def is_resolved(self) -> bool:
        return self.resolved_at is not None


@dataclass
class BuildReport:
    """Complete build report with all gaps and statistics"""
    component: str
    total_gaps: int = 0
    open_gaps: int = 0
    resolved_gaps: int = 0
    max_severity: int = 0
    gap_codes: List[str] = field(default_factory=list)
    kappa_final: float = 0.0
    authorized: bool = False


class GAPTracker:
    """
    Tracks all BUILD GAP codes throughout the Ultra Orchestrator lifecycle.
    Per SKILL_TRAINING_LAWS_v03 §5: Every gap must be resolved before packaging.
    """

    # Resolution strategies per gap category
    FIX_STRATEGIES: Dict[str, str] = {
        "H": "Re-generate content directly in subagent, verify no {{var}} remains",
        "Q": "Improve analytical depth, add reasoning steps, re-evaluate κ",
        "AB": "Re-run with controlled variables, document causal chain",
        "CA": "Add skill-specific CoT with decision points and failure modes",
        "TI": "Align SKILL.md with TRAINING_PROMPT.md, verify consistency",
        "PL": "Search-and-replace all placeholder strings, re-verify",
        "SC": "Add adversarial test cases, verify non-gaming behavior",
        "ML": "Document actual learning process with measurable metrics",
        "ME": "Add meta-evaluation layer with false positive/negative cases",
    }

    def __init__(self, kappa_threshold: float = 0.95):
        self.kappa_threshold = kappa_threshold
        self._gaps: Dict[str, GAPRecord] = {}  # id → record
        self._gap_counter = 0

    def detect(self, gap_code: str, component: str, description: str = "",
               kappa_before: float = 0.0) -> str:
        """
        Detect and record a gap.
        Returns gap_id for tracking.
        """
        if gap_code not in GAP_CODES:
            logger.warning(f"Unknown gap code: {gap_code}")
            gap_info = {"name": "UNKNOWN", "cat": "?", "severity": 3, "desc": "Unknown gap"}
        else:
            gap_info = GAP_CODES[gap_code]

        self._gap_counter += 1
        gap_id = f"GAP-{self._gap_counter:04d}"

        desc = description or gap_info.get("desc", "")
        fix = self.FIX_STRATEGIES.get(gap_info.get("cat", "?"), "Manual review required")

        record = GAPRecord(
            gap_code=gap_code,
            component=component,
            description=desc,
            severity=gap_info.get("severity", 3),
            detected_at=time.time(),
            kappa_before=kappa_before,
            fix_strategy=fix
        )
        self._gaps[gap_id] = record

        logger.warning(f"GAP DETECTED [{gap_code}] {component}: {desc} (severity={record.severity})")
        return gap_id

    def resolve(self, gap_id: str, resolution: str, kappa_after: float = 0.0) -> bool:
        """Mark a gap as resolved."""
        if gap_id not in self._gaps:
            logger.error(f"Gap not found: {gap_id}")
            return False

        record = self._gaps[gap_id]
        record.resolved_at = time.time()
        record.resolution = resolution
        record.kappa_after = kappa_after

        logger.info(f"GAP RESOLVED [{record.gap_code}] {record.component}: {resolution}")
        return True

    def scan_for_placeholders(self, content: str, component: str) -> List[str]:
        """Scan content for placeholder strings (PL-01 detection)."""
        placeholder_patterns = [
            r'\{\{[^}]+\}\}',           # Jinja2 unfilled
            r'YOUR_[A-Z_]+_HERE',        # YOUR_API_KEY_HERE
            r'INSERT_[A-Z_]+',           # INSERT_TOKEN
            r'example\.com',
            r'Lorem\s+ipsum',
            r'Sample\s+(text|data|output)',
            r'PLACEHOLDER',
            r'TODO:\s*fill',
            r'XXX_FILL_XXX',
            r'\[YOUR\s+\w+\s+HERE\]',
        ]
        found = []
        for pattern in placeholder_patterns:
            if re.search(pattern, content, re.I):
                found.append(pattern)
                self.detect("PL-01", component,
                           f"Placeholder pattern found: {pattern}")
        return found

    def scan_for_template_unfilled(self, content: str, component: str) -> bool:
        """Check for unfilled template variables (H-02)."""
        unfilled = re.findall(r'\{\{\s*\w+\s*\}\}', content)
        if unfilled:
            self.detect("H-02", component,
                       f"Unfilled template variables: {unfilled}")
            return True
        return False

    def check_kappa_authorization(self, kappa: float, component: str) -> bool:
        """Check if κ meets packaging threshold (Q-01)."""
        if kappa < self.kappa_threshold:
            self.detect("Q-01", component,
                       f"κ={kappa:.4f} < threshold={self.kappa_threshold}",
                       kappa_before=kappa)
            return False
        return True

    def check_ab_validity(self, run_a: dict, run_b: dict, component: str) -> bool:
        """Validate A/B run integrity (AB-01, AB-02, AB-03)."""
        valid = True

        # AB-01: Check both runs actually produced output
        if not run_a.get("output") or not run_b.get("output"):
            self.detect("AB-01", component, "One or both runs produced no output")
            valid = False

        # AB-02: Check only one variable changed
        if run_a.get("variables_changed", 0) > 1:
            self.detect("AB-02", component,
                       f"Run A changed {run_a['variables_changed']} variables")
            valid = False

        # AB-03: Check causal explanation exists
        if not run_a.get("causal_explanation") or not run_b.get("causal_explanation"):
            self.detect("AB-03", component, "Missing causal explanation for divergence")
            valid = False

        return valid

    def check_cognitive_architecture(self, reasoning: str, component: str) -> bool:
        """Check reasoning has proper cognitive architecture (CA-01, CA-02, CA-03)."""
        valid = True

        # CA-01: Not generic CoT
        generic_markers = ["step by step", "first i will", "then i will",
                          "finally i will", "in conclusion"]
        generic_count = sum(1 for m in generic_markers if m in reasoning.lower())
        if generic_count >= 3 and len(reasoning) < 200:
            self.detect("CA-01", component,
                       f"Generic CoT detected ({generic_count} markers)")
            valid = False

        # CA-02: Has decision points
        decision_markers = ["decide", "choose", "select", "if ", "else:",
                           "unless", "whether", "compare"]
        has_decisions = any(m in reasoning.lower() for m in decision_markers)
        if not has_decisions:
            self.detect("CA-02", component,
                       "No decision points in reasoning")
            valid = False

        # CA-03: Addresses failure modes
        failure_markers = ["error", "exception", "fail", "timeout",
                          "invalid", "missing", "edge case"]
        has_failures = any(m in reasoning.lower() for m in failure_markers)
        if not has_failures:
            self.detect("CA-03", component,
                       "Failure modes not addressed")
            valid = False

        return valid

    def get_component_report(self, component: str) -> BuildReport:
        """Get gap report for a specific component."""
        gaps = [g for g in self._gaps.values() if g.component == component]
        open_gaps = [g for g in gaps if not g.is_resolved]
        resolved = [g for g in gaps if g.is_resolved]

        return BuildReport(
            component=component,
            total_gaps=len(gaps),
            open_gaps=len(open_gaps),
            resolved_gaps=len(resolved),
            max_severity=max((g.severity for g in gaps), default=0),
            gap_codes=list(set(g.gap_code for g in gaps)),
            authorized=len(open_gaps) == 0 and len(gaps) > 0
        )

    def get_global_report(self) -> dict:
        """Get global gap statistics."""
        all_gaps = list(self._gaps.values())
        open_gaps = [g for g in all_gaps if not g.is_resolved]

        by_category: Dict[str, int] = {}
        for g in all_gaps:
            cat = g.gap_code.split("-")[0]
            by_category[cat] = by_category.get(cat, 0) + 1

        by_severity: Dict[int, int] = {}
        for g in all_gaps:
            by_severity[g.severity] = by_severity.get(g.severity, 0) + 1

        return {
            "total_gaps": len(all_gaps),
            "open_gaps": len(open_gaps),
            "resolved_gaps": len(all_gaps) - len(open_gaps),
            "max_severity": max((g.severity for g in all_gaps), default=0),
            "by_category": by_category,
            "by_severity": by_severity,
            "can_package": len(open_gaps) == 0,
            "open_critical": any(g.severity >= 4 for g in open_gaps),
            "components_affected": list(set(g.component for g in all_gaps)),
        }

    def export_report(self, filepath: str):
        """Export full gap report to JSON."""
        report = {
            "global": self.get_global_report(),
            "gaps": {gid: g.to_dict() for gid, g in self._gaps.items()},
            "gap_definitions": GAP_CODES,
            "timestamp": time.time(),
        }
        with open(filepath, "w") as f:
            json.dump(report, f, indent=2)
        logger.info(f"GAP report exported to {filepath}")

    def all_resolved(self) -> bool:
        """Check if all gaps are resolved (packaging gate)."""
        return all(g.is_resolved for g in self._gaps.values())

    def get_open_gaps(self) -> List[GAPRecord]:
        return [g for g in self._gaps.values() if not g.is_resolved]


__all__ = ["GAPTracker", "GAPRecord", "GAP_CODES", "GAPCategory", "BuildReport"]
